### ISSUE TITLE
GUILD_PRESENCES intent loops the connection

### ISSUE THREAD

**Issue by Westlanderz** [DiscordPP/discordpp#35]
If you use the intent GUILD_PRESENCES the echo bot starts looping the connection to discord. After the first heartbeat it says the following: 
"Sending: Client: Closed connection with status code 4014
Reconnecting because "The stream closed" ...
Fetching gateway...
 Done." and the next heartbeat it says the following: 
"Discord Servers notified of an invalid session ID.
Reconnecting because "The session is invalid" ...
Fetching gateway...
 Done."
This keeps alternating until you kill the bot, see the screenshot below. I hope this was enough information and reproducible, for more questions you can reach me on discord SenpaiR6#1717
![Screenshot_2021-05-27_11-06-22](https://user-images.githubusercontent.com/58142586/119798636-9c0ac980-bedb-11eb-90df-a1247707b709.png)

**Comment by UndarkAido** [comment]
That's a privileged intent. Is your bot set up to use it in the Developer Portal? https://discord.com/developers/docs/topics/gateway#privileged-intents
